esphome:
  name: fan_living_room
  friendly_name: Fan Living Room

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret

ota:
  - platform: esphome
    password: "!secret"

wifi:
  ssid: !secret
  password: !secret
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0
    dns1: 192.168.x.x


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  



substitutions:
  fan_name: "Fan Living Room"
  light_name: "Fan Living Room Light"
  power_light_name: "Fan Living Room Light power"
  power_fan_name: "Fan Living Room power"
  skyfan_model: "SKY1303"
  fan_rssi: "Fan Living Room rssi"



fan:
  - id: skyfan
    platform: speed
    output: skyfan_speed
    direction_output: skyfan_direction
    name: ${fan_name}
    restore_mode: NO_RESTORE
    disabled_by_default: false
    speed_count: 6

output:
  # When the fan speed is changed by the fan entity in Home Assistant, update
  # the tuyamcu datapoints that control the fan motor.
  - id: skyfan_speed
    platform: template
    type: float
    write_action: 
      then:
        - if:
            condition:
              - switch.is_on: update_fan
            then:
              - switch.turn_off: update_fan            
            else:             
              - logger.log:
                  format: "skyfan_speed is %1f"
                  args: [ 'state' ]
              - select.set_index:
                  id: datapoint_direction
                  index: !lambda |-
                    return (id(skyfan).direction != FanDirection::FORWARD ? 1 : 0);              
              - if:
                  condition:
                    lambda: 'return state < 0.1 ;'
                  then:
                    - switch.turn_off: datapoint_onoff
                  else:
                    - switch.turn_on: datapoint_onoff                                     
                    - if:
                        condition:
                          lambda: 'return (state < 0.3);'
                        then:
                          - select.set_index:
                              id: datapoint_mode
                              index: 0
                          - number.set:
                              id: datapoint_speed
                              value: 1
                        else:
                          - if:
                              condition:
                                lambda: 'return (state < 0.4);'
                              then:
                                - select.set_index:
                                    id: datapoint_mode
                                    index: 1
                              else:                        
                                - select.set_index:
                                    id: datapoint_mode
                                    index: 0
                                - if:
                                    condition:
                                      lambda: 'return (state < 0.6);'
                                    then:
                                      - number.set:
                                          id: datapoint_speed
                                          value: 2
                                    else:                  
                                      - if:
                                          condition:
                                            lambda: 'return (state < 0.8);'
                                          then:
                                            - number.set:
                                                id: datapoint_speed
                                                value: 3
                                          else:                              
                                            - if:
                                                condition:
                                                  lambda: 'return (state < 0.9);'
                                                then:
                                                  - number.set:
                                                      id: datapoint_speed
                                                      value: 4
                                                else:                              
                                                  - number.set:
                                                      id: datapoint_speed
                                                      value: 5        

  - id: skyfan_direction
    platform: template
    type: binary
    write_action: []

tuya:
  id: tuyamcu
  on_datapoint_update:
    - sensor_datapoint: 1
      datapoint_type: bool
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 2
      datapoint_type: enum
      then:
        - switch.turn_on: update_fan 
    - sensor_datapoint: 3
      datapoint_type: int
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 8
      datapoint_type: enum
      then:
        - switch.turn_on: update_fan
    - sensor_datapoint: 22
      datapoint_type: enum
      then: []


    - sensor_datapoint: 15
      datapoint_type: bool
      then: []   



switch:
  # A datapoint has changed in tuyamcu. Update the fan entity in Home Assistant 
  # to be consistent with the new datapoint values.
  - id: update_fan
    platform: template
    optimistic: true
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition: 
              - switch.is_on: datapoint_onoff
            then:
              - if:
                  condition:
                    - lambda: 'return ( id(datapoint_mode).active_index() == 1 );'
                  then:
                    - logger.log: "update_fan ECO therefore set speed 2"
                    - fan.turn_on: 
                        id: skyfan
                        speed: '2'
                        direction: !lambda |-
                          bool val = ( id(datapoint_direction).active_index() != 0 );
                          return val ? FanDirection::REVERSE : FanDirection::FORWARD;
                  else:
                    - if:
                        condition:
                          - lambda: 'return ( id(datapoint_speed).state == 1 );'
                        then:
                          - logger.log: "update_fan Set speed 1"
                          - fan.turn_on: 
                              id: skyfan
                              speed: '1'
                              direction: !lambda |-
                                bool val = ( id(datapoint_direction).active_index() != 0 );
                                return val ? FanDirection::REVERSE : FanDirection::FORWARD;
                        else:
                          - logger.log: "update_fan Set speed plus 1"
                          - fan.turn_on: 
                              id: skyfan
                              speed: !lambda |-
                                return (id(datapoint_speed).state + 1);
                              direction: !lambda |-
                                bool val = ( id(datapoint_direction).active_index() != 0 );
                                return val ? FanDirection::REVERSE : FanDirection::FORWARD;
            else:
              - logger.log: "update_fan Turn off"
              - fan.turn_off: 
                  id: skyfan            

  - id: datapoint_onoff
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Switch
    switch_datapoint: 1
    internal: true
  
select:
  - id: datapoint_mode
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Mode
    enum_datapoint: 2
    options:
      0: NORMAL
      1: ECO
      2: SLEEP
    disabled_by_default: true

  - id: datapoint_direction
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Direction
    enum_datapoint: 8
    options:
      0: FORWARD
      1: REVERSE
    internal: true

  - id: datapoint_timer
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Timer
    enum_datapoint: 22
    options:
      0: NIL
      1: 1_HOUR
      2: 2_HOUR
      3: 3_HOUR
      4: 4_HOUR
      5: 5_HOUR
      6: 6_HOUR
      7: 7_HOUR
      8: 8_HOUR
      9: 9_HOUR
      10: 10_HOUR
      11: 11_HOUR
      12: 12_HOUR
    disabled_by_default: true



  - id: datapoint_light_color_temperature
    platform: tuya
    tuya_id: tuyamcu
    name: ${light_name} Color Temperature
    enum_datapoint: 19
    options:
      0: 'COOL WHITE (3000K)'
      1: 'NATURAL WHITE (4200K)'
      2: 'WARM WHITE (6500K)'
    disabled_by_default: true 

#tuya:
 


number:

  - id: datapoint_speed
    platform: tuya
    tuya_id: tuyamcu
    name: ${fan_name} Speed
    number_datapoint: 3
    min_value: 0
    max_value: 5
    step: 1
    internal: true


#substitutions:
  

light:
  - id: fan_living_room_light
    platform: tuya
    name: ${light_name}
    switch_datapoint: 15
    dimmer_datapoint: 16
    min_value: 0
    max_value: 5
    color_temperature_datapoint: 19
    color_temperature_max_value: 2
    color_temperature_invert: true
    color_mode: BRIGHTNESS # [color_mode] is an invalid option for [light.tuya]. 
    restore_mode: ALWAYS_OFF
    disabled_by_default: false

#select:
# tuya:
#   id: tuyamcu
#   on_datapoint_update:
#     - sensor_datapoint: 15
#       datapoint_type: bool
#       then: []



sensor:




#sensor:
  - id: fan_power
    platform: template
    name: power_fan_living_room
    update_interval: 30s
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      float SKY903[7] = {0,3,4.8,7,12,19.5,32};
      float SKY1203[7] = {0,3.6,5.4,8,15,22,32.5};
      float SKY1303[7] = {0,3.9,5.8,9,15.6,25.2,31.8};
      float SKY1503[7] = {0,3.9,6,9,16,26,44.2};
      float SKY1204[7] = {0,3.8,5.8,9,17,27,30};
      float SKY1404[7] = {0,3.5,5.5,8,15,23,38};      
      if (id(skyfan).state) {
        return $skyfan_model[ id(skyfan).speed ]; 
      } else {
        return 0.0;
      }
    disabled_by_default: true                  

  - platform: wifi_signal
    name: "Fan Living Room rssi"
    update_interval: 60s


#sensor:
  - id: power_light
    platform: template
    name: ${power_light_name}
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 1
    disabled_by_default: true

interval:
  - interval: 30s
    then:
      - if:
          condition:
            light.is_on: fan_living_room_light
          then:
            - sensor.template.publish:
                id: power_light
                state: !lambda |-
                  return (id(fan_living_room_light).current_values.get_brightness() * 20); 
          else:
            - sensor.template.publish:
                id: power_light
                state: !lambda |-
                  return 0.0;
